language: scala

jdk:
  - oraclejdk8

install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - mvn install -P travis -B -f driver/pom.xml
  - cd tests-scala ; sbt test
