language: scala

os:
  - linux
jdk:
  - oraclejdk8
 
install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

before-install:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx3G"

script:
  - mvn install -P travis -B -f driver/pom.xml -Dfailsafe.timeout=0
  - cd tests-scala ; sbt test
