language: scala

os:
  - linux
jdk:
  - oraclejdk8
 
before_script:
  - echo "MAVEN_OPTS='-Xmx3g -XX:MaxDirectMemorySize=2g'" > ~/.mavenrc

install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - mvn install -P travis -B -f driver/pom.xml -Dfailsafe.timeout=0
  - cd tests-scala ; sbt test
