language: java

os:
  - linux

jdk:
  - openjdk8
 
before_script:
  - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

install:
#  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml -Dfailsafe.timeout=0

script:
  - travis_wait 30 mvn install -Dfailsafe.timeout=0
